SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

CREATE DATABASE IF NOT EXISTS `rtaixml` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `rtaixml`;

CREATE TABLE IF NOT EXISTS `data_innodb` (
  `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `server` varchar(255) NOT NULL DEFAULT '',
  `signalId` int(11) NOT NULL,
  `seqLoop` int(11) NOT NULL,
  `seq` int(11) NOT NULL,
  `value` double NOT NULL,
  PRIMARY KEY (`server`,`signalId`,`seqLoop`,`seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `data_myisam` (
  `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `server` varchar(255) NOT NULL DEFAULT '',
  `signalId` int(11) NOT NULL,
  `seqLoop` int(11) NOT NULL,
  `seq` int(11) NOT NULL,
  `value` double NOT NULL,
  PRIMARY KEY (`server`,`signalId`,`seqLoop`,`seq`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
